import {
  getCoffee,
  creditCard,
  onlineLibrary,
  workPlin,
  selfcare,
  amazingGraph,
  acessibilidadeModal,
  acessibilidadeForm,
  counter,
  animaisFantasticos,
  todo,
  quizz,
  orcamento,
  tictactoe,
  doe,
  proffy,
  beTheHero,
} from "../../assets/images";

export const projects = [
  {
    imageUrl: getCoffee,
    name: "get coffee",
    previewUrl: "https://lucianesantcs.github.io/get-coffee-source/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/get-coffee-source/",
    urlName: "github",
    urlNameHover: "Código",
    designUrl: "https://www.figma.com/file/lVkh41YvYiMposXwaJXOYO/get-coffee-layout?node-id=0%3A1",
    designName: "figma",
    designNameHover: "Design",
    description: "Código da landing page Get Coffee do desafio no DevChallenge",
    tags: ["html", "css", "grid", "font-end", "mine", "ui-design", "responsive", "challenges"],
  },
  {
    imageUrl: creditCard,
    name: "credit card checkout",
    previewUrl: "https://dribbble.com/shots/14206123-Credit-Card-Checkout",
    previewNameHover: "Preview",
    designUrl: "https://www.figma.com/file/zzMpg4F3L0n1DwNFjeQr85/credit-card",
    designName: "figma",
    designNameHover: "Design",
    tags: ["ui-design", "front-end"],
    description: "Formulário de cartão de crédito de uma loja de roupas",
  },
  {
    imageUrl: onlineLibrary,
    name: "sing up modal",
    previewUrl: "https://dribbble.com/shots/14189122-Online-Library-Modal",
    previewNameHover: "Preview",
    designUrl: "https://www.figma.com/file/CGZvEtvbSiMTJ3wlJA41wR/online-library-modal",
    designName: "figma",
    designNameHover: "Design",
    tags: ["ui-design", "front-end"],
    description: "Modal de sign up de uma livraria online",
  },
  {
    imageUrl: workPlin,
    name: "work plin",
    previewUrl: "https://lucianesantcs.github.io/work-plin/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/work-plin/",
    urlName: "github",
    urlNameHover: "Código",
    tags: ["html", "css", "flexbox", "grid", "font-end", "mine", "responsive", "challenges"],
    description: "Landing page de locação de co-work online",
  },
  {
    imageUrl: selfcare,
    name: "selfcare landing page",
    previewUrl: "https://lucianesantcs.github.io/selfcare/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/selfcare/",
    urlName: "github",
    urlNameHover: "Código",
    description: "Landing page de uma loja online para produtos de beleza",
    tags: ["html", "css", "flexbox", "font-end", "mine", "responsive", "challenges"],
  },
  {
    imageUrl: amazingGraph,
    name: "amazing-graph",
    previewUrl: "https://lucianesantcs.github.io/amazing-graph/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/amazing-graph/",
    urlName: "github",
    urlNameHover: "Código",
    description: "Landing page para site de criação de gráficos",
    tags: ["html", "css", "sass", "flexbox", "font-end", "mine", "responsive"],
  },
  {
    imageUrl: acessibilidadeModal,
    name: "acessibilidade modal",
    url: "https://github.com/lucianesantcs/acessibilidade-modal",
    urlName: "github",
    urlNameHover: "Código",
    description: "Modal construído seguindo as regras de acessibilidade do WCAG",
    tags: ["angular", "javascript", "font-end", "mine", "contributed", "acessibilidade", "alura"],
  },
  {
    imageUrl: acessibilidadeForm,
    name: "acessibilidade form",
    url: "https://github.com/lucianesantcs/acessibilidade-form",
    urlName: "github",
    urlNameHover: "Código",
    description: "Simples form construído seguindo as regras de acessibilidade do WCAG",
    tags: ["angular", "javascript", "font-end", "mine", "contributed", "acessibilidade", "alura"],
  },
  {
    imageUrl: counter,
    name: "countdown app",
    previewUrl: "https://lucianesantcs.github.io/contador/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/contador/",
    urlName: "github",
    urlNameHover: "Código",
    description: "App de countdown com vanilla javascript",
    tags: ["flexbox", "javascript", "font-end", "mine", "challenges"],
  },
  {
    imageUrl: animaisFantasticos,
    name: "animais fantásticos",
    previewUrl: "https://lucianesantcs.github.io/animais-fantasticos/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/animais-fantasticos",
    urlName: "github",
    urlNameHover: "Código",
    description: "Site desenvolvido no curso de JavaScript ES6+ completo pela Origamid",
    tags: ["javascript", "nodejs", "webpack", "eslint", "babel", "font-end", "contributed"],
  },
  {
    imageUrl: todo,
    name: "to-do app",
    previewUrl: "https://christyanbrayan.github.io/to-do/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/to-do/",
    urlName: "github",
    urlNameHover: "Código",
    description: "Lista de To-Do desenvolvido no curso básico da Rocketseat",
    tags: ["flexbox", "javascript", "font-end", "local-storage", "contributed"],
  },
  {
    imageUrl: quizz,
    name: "quiz de programação",
    previewUrl: "https://lucianesantcs.github.io/quizz/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/quizz/",
    urlName: "github",
    urlNameHover: "Código",
    description: "Simples quiz desenvolvido com html, css, e javascript",
    tags: ["javascript", "mine", "font-end", "responsive", "contributed"],
  },
  {
    imageUrl: orcamento,
    name: "orçamento pessoal",
    previewUrl: "https://lucianesantcs.github.io/orcamento-pessoal/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/orcamento-pessoal/",
    urlName: "github",
    urlNameHover: "Código",
    tags: ["javascript", "bootstrap", "font-end", "local-storage", "contributed"],
    description: "Aplicativo que cadastra e permite a consulta de despesas",
  },
  {
    imageUrl: tictactoe,
    name: "tic tac toe game",
    previewUrl: "https://lucianesantcs.github.io/tic-tac-toe/",
    previewNameHover: "Live Preview",
    url: "https://github.com/lucianesantcs/tic-tac-toe/",
    urlName: "github",
    urlNameHover: "Código",
    description: "Jogo da velha desenvolvido com vanilla javascript",
    tags: ["javascript", "mine", "font-end", "contributed"],
  },
  {
    imageUrl: doe,
    name: "doe",
    url: "https://github.com/lucianesantcs/doe/",
    urlName: "github",
    urlNameHover: "Código",
    description: "Sistema de cadastro para doadores de sangue, desenvolvido na Maratona Dev",
    tags: ["javascript", "nodejs", "font-end", "back-end", "postgresql", "nunjucks", "contributed"],
  },
  {
    imageUrl: proffy,
    name: "proffy",
    url: "https://github.com/lucianesantcs/proffy/",
    urlName: "github",
    urlNameHover: "Código",
    tags: [
      "javascript",
      "nodejs",
      "reactjs",
      "font-end",
      "back-end",
      "sqlite",
      "react-native",
      "typescript",
      "express",
      "contributed",
      "responsive",
    ],
    description: "Aplicação que conecta alunos e professores",
  },
  {
    imageUrl: beTheHero,
    name: "be-the-hero",
    url: "https://github.com/lucianesantcs/be-the-hero/",
    urlName: "github",
    urlNameHover: "Código",
    description:
      "Aplicação que conecta ONG's a pessoas que estão dispostas a ajudá-los monetariamente nos casos",
    tags: [
      "javascript",
      "nodejs",
      "reactjs",
      "font-end",
      "back-end",
      "sqlite",
      "react-native",
      "express",
      "contributed",
      "responsive",
    ],
  },
];

export const buttons = [
  {
    value: "all",
    text: "todos os projetos",
    active: true,
  },

  {
    value: "mine",
    text: "meu código",
    active: false,
  },
  {
    value: "contributed",
    text: "contribuição",
    active: false,
  },
  {
    value: "ui-design",
    text: "layouts",
    active: false,
  },
  {
    value: "html",
    text: "html & css",
    active: false,
  },
  {
    value: "javascript",
    text: "javascript",
    active: false,
  },
  {
    value: "reactjs",
    text: "reactjs",
    active: false,
  },
  {
    value: "angular",
    text: "angular",
    active: false,
  },
  {
    value: "font-end",
    text: "font-end",
    active: false,
  },
  {
    value: "back-end",
    text: "back-end",
    active: false,
  },
];
